MathExample:
	gcc -Wall -std=c99 mathFP/mathfp.c -o MathExample

PatronExample:
	gcc -Wall -std=c99 patronFP/functionPointers.c patronFP/main.c -o PatronExample

clean:
	@rm -f MathExample
	@rm -f PatronExample