CompileWithoutWarnings:
	gcc -Wall -std=c99 goodStrdup.c -o Good

CompileWithWarnings:
	gcc -Wall -std=c99 badStrdup.c -o Bad

strcmpExample:
	gcc -Wall -std=c99 strcmpExample.c -o strcmpExample

clean:
	@rm -f Good
	@rm -f Bad
	@rm -f strcmpExample
	@rm -f *~